- name: Copie chatbot-back
  synchronize:
    src: '{{ gitDir }}/{{ backDir }}/'
    dest: '{{ appsDir }}/{{ backDir }}'
    rsync_opts:
      - '--exclude=mediatheque/'
      - '--exclude=historic/'
  when: updateBack

- name: Copie env-file
  copy:
    src: '{{ gitDir }}/.env'
    dest: '{{ appsDir }}/{{ backDir }}/.env'
  when: updateBack

- name: Copie chatbot-front
  synchronize:
    src: '{{ gitDir }}/{{ frontDir }}/dist/{{ frontDir }}/'
    dest: '{{ appsDir }}/{{ frontDir }}'
    delete: yes
  when: updateFront

- name: Copie webchat
  synchronize:
    src: '{{ gitDir }}/{{ frontDir }}/dist/{{ webchatDir }}/'
    dest: '{{ appsDir }}/{{ webchatDir }}'
    delete: yes
  when: updateFront

- name: Copie chatbot-template
  synchronize:
    src: '{{ gitDir }}/{{ botDir }}/'
    dest: '{{ appsDir }}/{{ botDir }}'
    rsync_opts:
      - '--exclude=models/'
  when: updateRasa

- name: Copie env-file bis
  copy:
    src: '{{ gitDir }}/.env'
    dest: '{{ appsDir }}/{{ botDir }}/.env'
  when: updateRasa

- name: npm install chatbot-back
  command:
    cmd: npm install
    chdir: '{{ appsDir }}/{{ backDir }}'
  when: updateBack

- name: npm build chatbot-back
  command:
    cmd: 'npm run build'
    chdir: '{{ appsDir }}/{{ backDir }}'
  when: updateBack

- name: npm copy env file
  command:
    cmd: 'npm run copy'
    chdir: '{{ appsDir }}/{{ backDir }}'
  when: updateBack

- name: Copie du fichier rasa endpoints.yml
  copy:
    src: '{{ appsDir }}/{{ botDir }}/endpoints.example.yml'
    dest: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    remote_src: yes
  when: updateRasa

- name: Mise à jour du fichier rasa endpoints.yml - DB_HOST
  lineinfile:
    path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    regexp: '^  url:'
    line: '  url: "{{ DATABASE_HOST }}"'
  when: updateRasa

- name: Mise à jour du fichier rasa endpoints.yml - DB_PORT
  lineinfile:
    path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    regexp: '^  port:'
    line: '  port: "{{ DATABASE_PORT }}"'
  when: updateRasa

- name: Mise à jour du fichier rasa endpoints.yml - DB_USERNAME
  lineinfile:
    path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    regexp: '^  username:'
    line: '  username: "{{ DATABASE_USER }}"'
  when: updateRasa

- name: Mise à jour du fichier rasa endpoints.yml - DB_PASSWORD
  lineinfile:
    path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    regexp: '^  password:'
    line: '  password: "{{ DATABASE_PASSWORD }}"'
  when: updateRasa

- name: Mise à jour du fichier rasa endpoints.yml - DB_NAME
  lineinfile:
    path: '{{ appsDir }}/{{ botDir }}/endpoints.yml'
    regexp: '^  db:'
    line: '  db: "{{ DATABASE_NAME }}"'
  when: updateRasa
