---

# Prerequisites: SSH access for user with password

- hosts: localhost

  vars:
    # BEATS
    - beats_version: 6.8.13
    - beat: filebeat
    - oss_version: true
    - beat_conf:
        logging.to_files: true
        setup.template.enabled: false
        filebeat:
          inputs:
            - type: log
              enabled: true
              paths:
                - /root/.pm2/logs/*.log
              document_type: nest_log
            - type: log
              enabled: true
              paths:
                - /var/www/chatbot-template/*.log
              document_type: rasa_log
    - output_conf: {"elasticsearch":{
      "hosts":["{{ ELASTIC_HOST }}"],
      "protocol": "https",
      "username":"{{ ELASTIC_USERNAME }}",
      "password":"{{ ELASTIC_PASSWORD }}",
      "index":"{{ ELASTIC_FILEBEAT_INDEX }}",
      "ssl.enabled": true
    }}

  roles:
    - role: elastic.beats
